# Place Installation Parameters for local testing.
# For eg., if you have defined `username` in your
# `iparam_en.yml`, you can define the value here:
# username: YOUR_INSTALLED_USERS_USERNAME
APIKey: '023e1a4e1dfc4ea6ae0a20e9cdff437d43d0d87a'